// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZlVesx6Td4m_CcgC-GMWqmssaRaj5Ng',
    appId: '1:412881082749:web:6e521dce726889a0745414',
    messagingSenderId: '412881082749',
    projectId: 'budgetin-id',
    authDomain: 'budgetin-id.firebaseapp.com',
    storageBucket: 'budgetin-id.firebasestorage.app',
    measurementId: 'G-MCYVSKM03L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4alJ7AsETXAfnmdQHxcnW9MSdFfhNhNc',
    appId: '1:412881082749:android:7cca858b41629665745414',
    messagingSenderId: '412881082749',
    projectId: 'budgetin-id',
    storageBucket: 'budgetin-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwlYyDUsyzJg8aKAMqMd7XwO1Y3mWy2pY',
    appId: '1:412881082749:ios:0d1a3c76542fbb2d745414',
    messagingSenderId: '412881082749',
    projectId: 'budgetin-id',
    storageBucket: 'budgetin-id.firebasestorage.app',
    iosBundleId: 'com.example.budgetinId',
  );
}
